DROP TABLE IF EXISTS `cards`;
CREATE TABLE IF NOT EXISTS `cards` (
	`all_parts` TEXT NULL,
	`arena_id` INT NULL,
	`artist_ids` TEXT NULL,
	`artist` TEXT NULL,
	`booster` BOOLEAN NOT NULL,
	`border_color` TEXT NOT NULL,
	`card_back_id` TEXT NOT NULL,
	`card_faces` TEXT NULL,
	`cardmarket_id` INT NULL,
	`cmc` FLOAT(27) NOT NULL,
	`collector_number` TEXT NOT NULL,
	`color_identity` TEXT NOT NULL,
	`color_indicator` TEXT NULL,
	`colors` TEXT NULL,
	`component` TEXT NOT NULL,
	`content_warning` BOOLEAN NULL,
	`digital` BOOLEAN NOT NULL,
	`edhrec_rank` INT NULL,
	`flavor_name` TEXT NULL,
	`flavor_text` TEXT NULL,
	`foil` BOOLEAN NOT NULL,
	`frame_effects` TEXT NULL,
	`frame` TEXT NOT NULL,
	`full_art` BOOLEAN NOT NULL,
	`games` TEXT NOT NULL,
	`hand_modifier` TEXT NULL,
	`highres_image` BOOLEAN NOT NULL,
	`id` TEXT NOT NULL,
	`illustration_id` TEXT NULL,
	`image_status` TEXT NOT NULL,
	`image_uris` TEXT NULL,
	`keywords` TEXT NOT NULL,
	`lang` TEXT NOT NULL,
	`layout` TEXT NOT NULL,
	`legalities` TEXT NOT NULL,
	`life_modifier` TEXT NULL,
	`loyalty` TEXT NULL,
	`mana_cost` TEXT NULL,
	`mtgo_foil_id` INT NULL,
	`mtgo_id` INT NULL,
	`multiverse_ids` TEXT NULL,
	`name` TEXT NOT NULL,
	`nonfoil` BOOLEAN NOT NULL,
	`object` TEXT NOT NULL,
	`oracle_id` TEXT NOT NULL,
	`oracle_text` TEXT NULL,
	`oversized` BOOLEAN NOT NULL,
	`power` TEXT NULL,
	`preview.previewed_at` DATE NULL,
	`preview` TEXT NULL,
	`prices` TEXT NOT NULL,
	`printed_name` TEXT NULL,
	`printed_text` TEXT NULL,
	`printed_type_line` TEXT NULL,
	`prints_search_uri` TEXT NOT NULL,
	`produced_mana` TEXT NULL,
	`promo_types` TEXT NULL,
	`promo` BOOLEAN NOT NULL,
	`purchase_uris` TEXT NOT NULL,
	`rarity` TEXT NOT NULL,
	`related_uris` TEXT NOT NULL,
	`released_at` DATE NOT NULL,
	`reprint` BOOLEAN NOT NULL,
	`reserved` BOOLEAN NOT NULL,
	`rulings_uri` TEXT NOT NULL,
	`scryfall_set_uri` TEXT NOT NULL,
	`scryfall_uri` TEXT NOT NULL,
	`set_id` TEXT NOT NULL,
	`set_name` TEXT NOT NULL,
	`set_search_uri` TEXT NOT NULL,
	`set_type` TEXT NOT NULL,
	`set_uri` TEXT NOT NULL,
	`set` TEXT NOT NULL,
	`story_spotlight` BOOLEAN NOT NULL,
	`tcgplayer_id` INT NULL,
	`textless` BOOLEAN NOT NULL,
	`toughness` TEXT NULL,
	`type_line` TEXT NOT NULL,
	`uri` TEXT NOT NULL,
	`variation` BOOLEAN NOT NULL,
	`watermark` TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
