DROP TABLE IF EXISTS `cards`;
CREATE TABLE IF NOT EXISTS `cards` (
	`all_parts` VARCHAR(255) NULL,
	`arena_id` INT NULL,
	`artist` VARCHAR(255) NULL,
	`artist_ids` VARCHAR(255) NULL,
	`booster` BOOLEAN NOT NULL,
	`border_color` VARCHAR(255) NOT NULL,
	`card_back_id` VARCHAR(255) NOT NULL,
	`card_faces` VARCHAR(255) NULL,
	`cardmarket_id` INT NULL,
	`cmc` FLOAT(5) NOT NULL,
	`collector_number` VARCHAR(255) NOT NULL,
	`color_identity` VARCHAR(255) NOT NULL,
	`color_indicator` VARCHAR(255) NULL,
	`colors` VARCHAR(255) NULL,
	`component` VARCHAR(255) NOT NULL,
	`content_warning` BOOLEAN NULL,
	`digital` BOOLEAN NOT NULL,
	`edhrec_rank` INT NULL,
	`flavor_name` VARCHAR(255) NULL,
	`flavor_text` VARCHAR(255) NULL,
	`foil` BOOLEAN NOT NULL,
	`frame_effects` VARCHAR(255) NULL,
	`frame` VARCHAR(255) NOT NULL,
	`full_art` BOOLEAN NOT NULL,
	`games` VARCHAR(255) NOT NULL,
	`hand_modifier` VARCHAR(255) NULL,
	`highres_image` BOOLEAN NOT NULL,
	`id` VARCHAR(255) NOT NULL,
	`illustration_id` VARCHAR(255) NULL,
	`image_status` VARCHAR(255) NOT NULL,
	`image_uris` VARCHAR(255) NULL,
	`keywords` VARCHAR(255) NOT NULL,
	`lang` VARCHAR(255) NOT NULL,
	`layout` VARCHAR(255) NOT NULL,
	`legalities` VARCHAR(255) NOT NULL,
	`life_modifier` VARCHAR(255) NULL,
	`loyalty` VARCHAR(255) NULL,
	`mana_cost` VARCHAR(255) NULL,
	`mtgo_foil_id` INT NULL,
	`mtgo_id` INT NULL,
	`multiverse_ids` VARCHAR(255) NULL,
	`name` VARCHAR(255) NOT NULL,
	`nonfoil` BOOLEAN NOT NULL,
	`object` VARCHAR(255) NOT NULL,
	`oracle_id` VARCHAR(255) NOT NULL,
	`oracle_text` VARCHAR(255) NULL,
	`oversized` BOOLEAN NOT NULL,
	`power` VARCHAR(255) NULL,
	`preview` VARCHAR(255) NULL,
	`preview.previewed_at` DATE NULL,
	`preview.source_uri` VARCHAR(255) NULL,
	`preview.source` VARCHAR(255) NULL,
	`prices` VARCHAR(255) NOT NULL,
	`printed_name` VARCHAR(255) NULL,
	`printed_text` VARCHAR(255) NULL,
	`printed_type_line` VARCHAR(255) NULL,
	`prints_search_uri` VARCHAR(255) NOT NULL,
	`produced_mana` VARCHAR(255) NULL,
	`promo_types` VARCHAR(255) NULL,
	`promo` BOOLEAN NOT NULL,
	`purchase_uris` VARCHAR(255) NOT NULL,
	`rarity` VARCHAR(255) NOT NULL,
	`related_uris` VARCHAR(255) NOT NULL,
	`released_at` DATE NOT NULL,
	`reprint` BOOLEAN NOT NULL,
	`reserved` BOOLEAN NOT NULL,
	`rulings_uri` VARCHAR(255) NOT NULL,
	`scryfall_set_uri` VARCHAR(255) NOT NULL,
	`scryfall_uri` VARCHAR(255) NOT NULL,
	`set_id` VARCHAR(255) NOT NULL,
	`set_name` VARCHAR(255) NOT NULL,
	`set_search_uri` VARCHAR(255) NOT NULL,
	`set_type` VARCHAR(255) NOT NULL,
	`set_uri` VARCHAR(255) NOT NULL,
	`set` VARCHAR(255) NOT NULL,
	`story_spotlight` BOOLEAN NOT NULL,
	`tcgplayer_id` INT NULL,
	`textless` BOOLEAN NOT NULL,
	`toughness` VARCHAR(255) NULL,
	`type_line` VARCHAR(255) NOT NULL,
	`uri` VARCHAR(255) NOT NULL,
	`variation_of` VARCHAR(255) NULL,
	`variation` BOOLEAN NOT NULL,
	`watermark` VARCHAR(255) NULL,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
